
# This field should be populated with the contract names for use in contract lookups.
contractNames = [
    "PAUSER_REGISTRY", 
    "BLS_APK_REGISTRY", 
    "INDEX_REGISTRY", 
    "STAKE_REGISTRY", 
    "SOCKET_REGISTRY", 
    "REGISTRY_COORDINATOR",
    "EJECTION_MANAGER", 
    "SERVICE_MANAGER",
    "OPERATOR_STATE_RETRIEVER",
    "THRESHOLD_REGISTRY",
    "RELAY_REGISTRY",
    "DISPERSER_REGISTRY",
    "PAYMENT_VAULT",
    "CERT_VERIFIER",
    "CERT_VERIFIER_V1",
    "CERT_VERIFIER_V2",
    "CERT_VERIFIER_ROUTER"
]

# This field should be populated with the addresses of the contracts in the same order as in contractNames.
contractAddresses = [
    "0x85Ef7299F8311B25642679edBF02B62FA2212F06", # PAUSER_REGISTRY
    "0x066cF95c1bf0927124DFB8B02B401bc23A79730D", # BLS_APK_REGISTRY
    "0x2E3D6c0744b10eb0A4e6F679F71554a39Ec47a5D", # INDEX_REGISTRY
    "0xBDACD5998989Eec814ac7A0f0f6596088AA2a270", # STAKE_REGISTRY
    "0x25aFC8944f501545DDB7E7C4C8A0119965AAb166", # SOCKET_REGISTRY
    "0x53012C69A189cfA2D9d29eb6F19B32e0A2EA3490", # REGISTRY_COORDINATOR
    "0x6979bF665e54cd15bd7194BD25C853870038558a", # EJECTION_MANAGER
    "0xD4A7E1Bd8015057293f0D0A557088c286942e84b", # SERVICE_MANAGER
    "0x003497Dd77E5B73C40e8aCbB562C8bb0410320E7", # OPERATOR_STATE_RETRIEVER
    "0x76d131CFBD900dA12f859a363Fb952eEDD1d1Ec1", # THRESHOLD_REGISTRY
    "0xaC8C6C7Ee7572975454E2f0b5c720f9E74989254", # RELAY_REGISTRY
    "0xFD1731f14be30fB4Fb8DB8d11E0487aC3A7795B6", # DISPERSER_REGISTRY
    "0x4a7Fff191BCDa5806f1Bc8689afc1417c08C61AB", # PAYMENT_VAULT
    "0x036bb27a1f03350bdcccf344b497ef22604006a3", # CERT_VERIFIER
    "0xFe52fE1940858DCb6e12153E2104aD0fDFbE1162", # CERT_VERIFIER_V1
    "0xFe52fE1940858DCb6e12153E2104aD0fDFbE1162", # CERT_VERIFIER_V2
    "0xDD735AFFe77A5ED5b21ED47219f95ED841f8Ffbd", # CERT_VERIFIER_ROUTER
]

# The address of the proxy admin contract that manages the upgradeability of the contracts.
proxyAdminAddress = "0xB043055dd967A382577c2f5261fA6428f2905c15"

# The privileged account that can manage the contract directory.
owner = "0xDA29BB71669f46F2a779b4b62f03644A84eE3479"