
# This field should be populated with the contract names for use in contract lookups.
contractNames = [
    "PAUSER_REGISTRY", 
    "BLS_APK_REGISTRY", 
    "INDEX_REGISTRY", 
    "STAKE_REGISTRY", 
    "SOCKET_REGISTRY", 
    "REGISTRY_COORDINATOR",
    "EJECTION_MANAGER", 
    "SERVICE_MANAGER",
    "OPERATOR_STATE_RETRIEVER",
    "THRESHOLD_REGISTRY",
    "RELAY_REGISTRY",
    "DISPERSER_REGISTRY",
    "PAYMENT_VAULT",
    "CERT_VERIFIER"
]

# This field should be populated with the addresses of the contracts in the same order as in contractNames.
contractAddresses = [
    "0x9Ab2FEAf0465f0eD51Fc2b663eF228B418c9Dad1", # PAUSER_REGISTRY
    "0xAd7f9e558170a149Ca8E90f41Ab2444A5d3bd6aD", # BLS_APK_REGISTRY
    "0x8cE5F2a53cBd29710eb94A04e40C07A4DdF15d10", # INDEX_REGISTRY
    "0x53668EBf2e28180e38B122c641BC51Ca81088871", # STAKE_REGISTRY
    "0x1747ef24dbbb52cB06382d323f455D48dE1AC7fd", # SOCKET_REGISTRY
    "0x2c61EA360D6500b58E7f481541A36B443Bc858c6", # REGISTRY_COORDINATOR
    "0xEEed164605833263B7690bB521983b777D128698", # EJECTION_MANAGER
    "0x54A03db2784E3D0aCC08344D05385d0b62d4F432", # SERVICE_MANAGER
    "0x003497Dd77E5B73C40e8aCbB562C8bb0410320E7", # OPERATOR_STATE_RETRIEVER
    "0x41AEE4A23770045e9977CC9f964d3380D6Ff9e4E", # THRESHOLD_REGISTRY
    "0xca1ca181fCb3c4192D320569c6eB4b5161B80328", # RELAY_REGISTRY
    "0xD45323B6d168bd6749294f66F27Dfa41b7dF2102", # DISPERSER_REGISTRY
    "0x46E024ca6e5E1172100930c28DCCcF49BE5462C9", # PAYMENT_VAULT
    "0xCCFE3d87fB7D369f1eeE65221a29A83f1323043C", # CERT_VERIFIER
]

# The address of the proxy admin contract that manages the upgradeability of the contracts.
proxyAdminAddress = "0x9Fd7E279f5bD692Dc04792151E14Ad814FC60eC1"

# The privileged account that can manage the contract directory.
owner = "0xDA29BB71669f46F2a779b4b62f03644A84eE3479"