environment:
  name: "staging"
  type: "local"

deployers:
- name: "default"
  rpc: http://localhost:8545
  verifyContracts: false
  verifierUrl: http://localhost:4000/api
  deploySubgraphs: true
  slow: false

eigenda:
  deployer: "default"

blobVersions:
  - codingRate: 8
    numChunks: 8192
    maxNumOperators: 3537

privateKeys:
  ecdsaMap:
    default:
      privateKey: 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
    batcher0:
      privateKey: 0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d

services:
  counts:
    operators: 4
    maxOperatorCount: 3
    relays: 4
  stakes:
    - total: 100e18
      distribution: [1, 4, 6, 10]
    - total: 100e18
      distribution: [2, 3, 5, 8]
  basePort: 32000
  variables:
    globals:
      HOSTNAME: host.docker.internal
      TIMEOUT: 20s
      CHAIN_RPC: http://host.docker.internal:8545
      CHAIN_ID: 40525
      G1_PATH: resources/kzg/g1.point.300000
      G2_PATH: resources/kzg/g2.point.300000
      G2_POWER_OF_2_PATH: resources/kzg/g2.point.300000.powerOf2
      CACHE_PATH: resources/kzg/SRSTables
      SRS_ORDER: 10000
      SRS_LOAD: 10000
      CHALLENGE_ORDER: 10000
      LOG_LEVEL: "debug"
      VERBOSE: true
      NUM_CONNECTIONS: 50
      AWS_ENDPOINT_URL: http://host.docker.internal:4570
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: localstack
      AWS_SECRET_ACCESS_KEY: localstack
      ENCODER_ADDRESS: host.docker.internal:34000
      GRAPH_URL: http://host.docker.internal:8000/subgraphs/name/Layr-Labs/eigenda-operator-state
      USE_GRAPH: true
      PUBLIC_IP_CHECK_INTERVAL: 0
