environment:
  name: "staging"
  type: "local"

deployers:
- name: "default"
  rpc: http://localhost:8545
  verifyContracts: false
  verifierUrl: http://localhost:4000/api
  deploySubgraphs: false
  slow: false

eigenda:
  deployer: "default"

privateKeys:
  ecdsaMap:
    default:
      privateKey: 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
    batcher0:
      privateKey: 0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d

services:
  counts:
    dispersers: 1
    operators: 4
  stakes:
    total: 100e18
    distribution: [1.3, 2, 3, 5]
  basePort: 32000
  variables:
    globals:
      HOSTNAME: localhost
      TIMEOUT: 20s
      CHAIN_RPC: http://localhost:8545
      CHAIN_ID: 40525
      G1_PATH: resources/kzg/g1.point
      G2_PATH: resources/kzg/g2.point
      CACHE_PATH: resources/kzg/SRSTables
      SRS_ORDER: 3000
      CHALLENGE_ORDER: 3000
      STD_LOG_LEVEL: "trace"
      FILE_LOG_LEVEL: "trace"
      VERBOSE: true
      NUM_CONNECTIONS: 50
      AWS_ENDPOINT_URL: http://localhost:4570
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: localstack
      AWS_SECRET_ACCESS_KEY: localstack
      ENCODER_ADDRESS: 0.0.0.0:34000
      USE_GRAPH: false
