environment:
  name: "staging"
  type: "local"

deployers:
- name: "default"
  rpc: http://localhost:8545
  verifyContracts: false
  verifierUrl: http://localhost:4000/api
  slow: false

eigenda:
  deployer: "default"

privateKeys:

services:
  counts:
    dispersers: 1
    operators: 4
  stakes:
    total: 100e18
    distribution: [1.3, 2, 3, 5]
  basePort: 32000
  variables:
    globals:
      HOSTNAME: localhost
      TIMEOUT: 20s
      CHAIN_RPC: http://localhost:8545
      CHAIN_ID: 40525
      G1_PATH: resources/kzg/g1.point
      G2_PATH: resources/kzg/g2.point
      CACHE_PATH: resources/kzg/SRSTables
      SRS_ORDER: 3000
      CHALLENGE_ORDER: 3000
      STD_LOG_LEVEL: "trace"
      VERBOSE: true
