### CORE ###

# Only this address can finalize the deployment and be the owner of the deployed contracts.
initialOwner = "0x30d769FBb94af0e759AbBd4F3a1fC591413A04e5"

# Parameters shared across various deployed contracts
[initParams.shared]
rewardsCoordinator = "0xfC4C575ea3f8316D38F83076Cf765f7B8DeaFC58"
avsDirectory = "0xF2d1511E53AeAE16213EcA7963A103cB5CEc2b18"
delegationManager = "0xB4D5cABA07826838AcA633E7a6055Ae38f9F5b95"
initialPausedStatus = 0

# Parameters for the pauser registry contract
[initParams.core.pauserRegistry]
pausers = ["0x33225d93b93C32FF7AD9bd644C956beA315b4042"]
unpauser = "0xA0810EdE1B4A58872d733F11ad004A3bf201308e"

### MIDDLEWARE ###

# Parameters for the registry coordinator contract
[initParams.middleware.registryCoordinator]
churnApprover = "0x54FbFCa8E9A272600708F65411e17A80c2522239"
ejector = "0x9d534F112b680DcCD6A7C488605F534588Bd8d7f"
minimumStakes = [0]
strategyParams = [
    [
        { 0_strategy = "0x90f8B250206735ACC1743D9a31691E8D1EF8E387", 1_multiplier = 1 }
    ]
]
operatorSetParams = [
    { 0_maxOperatorCount = 0, 1_kickBIPsOfOperatorStake = 0, 2_kickBIPsOfTotalStake = 0 }
]

# Parameters for the ejection manager contract
[initParams.middleware.ejectionManager]
ejectors = [] # Settable by owner
quorumEjectionParams = [] # Settable by owner

### EIGEN DA ###

# Parameters for the Threshold Registry contract
[initParams.eigenDA.thresholdRegistry]
quorumAdversaryThresholdPercentages = "0x"
quorumConfirmationThresholdPercentages = "0x"
quorumNumbersRequired = "0x"
versionedBlobParams = [
    { 0_maxNumOperators = 0, 1_numChunks = 0, 2_codingRate = 0 }
]

# Parameters for the payment vault contract
[initParams.eigenDA.paymentVault]
minNumSymbols = 0
pricePerSymbol = 0
priceUpdateCooldown = 0
globalSymbolsPerPeriod = 0
reservationPeriodInterval = 0
globalRatePeriodInterval = 0

# Parameters for the rewards initiator contract
[initParams.eigenDA.serviceManager]
rewardsInitiator = "0x8C8c2D07b69983c97C06d5B8AFD8Da85D8385Deb"
batchConfirmers = ["0x42b5eC487B9bA90Cba1D0B8603ad793e640285eC"]